name: Laravel Basic CI

on:
  push:
    branches:
      - main

jobs:
  laravel:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Verify PHP
        run: php -v

      - name: Install Composer Dependencies
        run: composer install

      - name: Verify Laravel
        run: php artisan --version