name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Show PHP Version
        run: php -v

      - name: Print Success Message
        run: echo "Workflow Completed Successfully"