name: Secrets Variable Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Username
        run: echo "${{ vars.USERNAME }}"
      
      - name: Print Password
        run: echo "${{ vars.PASSWORD }}"